version: '3.8'
services:
  web:
    image: ubuntu/apache2
    ports:
      - "81:80"
    volumes:
      - ./html:/var/www/html
      - ./sites-avaible/000-default.conf:/etc/apache2/sites-available/000-default.conf